services:
  nginx:
    container_name: nginx_itpelag_practice
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app

  app:
    container_name: app_itpelag_practice
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  db:
    container_name: db_itpelag_practice
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itpelag_practice
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    container_name: redis_itpelag_practice
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db_data: